triage:
  label: triage
  dryRun: false

closeAndLock:
  labels:
    - label: 'ionitron: support'
      message: >
        Thanks for the issue! This issue appears to be a support request. We use this issue tracker exclusively for
        bug reports and feature requests. Please use our [forum](https://forum.ionicframework.com/) for help or
        questions about Ionicons.


        Thank you for using Ionicons!
    - label: 'ionitron: missing template'
      message: >
        Thanks for the issue! It appears that you have not filled out the provided issue template. We use this issue
        template in order to gather more information and further assist you. Please create a new issue and ensure the
        template is fully filled out.


        Thank you for using Ionicons!
  close: true
  lock: true
  dryRun: false

comment:
  labels:
    - label: "help wanted"
      message: >
        This issue has been labeled as `help wanted`. This label is added to issues
        that we believe would be good for contributors.


        If you'd like to work on this issue, please comment here letting us know that
        you would like to submit a pull request for it. This helps us to keep track of
        the pull request and make sure there isn't duplicated effort.


        For a guide on how to create a pull request and test this project locally to see
        your changes, see our [contributing documentation](https://github.com/ionic-team/ionicons/blob/main/.github/CONTRIBUTING.md#creating-a-pull-request).


        Thank you!
    - label: 'ionitron: needs reproduction'
      message: >
        Thanks for the issue! This issue has been labeled as `needs reproduction`. This label is added to issues that
        need a code reproduction.


        Please reproduce this issue and provide a way for us to access it (GitHub repo, StackBlitz, etc). Without a
        reliable code reproduction, it is unlikely we will be able to resolve the issue, leading to it being closed.


        If you have already provided a code snippet and are seeing this message, it is likely that the code snippet was
        not enough for our team to reproduce the issue.
  dryRun: false

noReply:
  days: 14
  maxIssuesPerRun: 100
  label: "needs: reply"
  responseLabel: triage
  exemptProjects: true
  exemptMilestones: true
  message: >
    Thanks for the issue! This issue is being closed due to the lack of a reply. If this is still
    an issue with the latest version of Ionicons, please create a new issue and ensure the
    template is fully filled out.


    Thank you for using Ionicons!
  close: true
  lock: true
  dryRun: false

noReproduction:
  days: 14
  maxIssuesPerRun: 100
  label: "ionitron: needs reproduction"
  responseLabel: triage
  exemptProjects: true
  exemptMilestones: true
  message: >
    Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still
    an issue with the latest version of Ionicons, please create a new issue and ensure the
    template is fully filled out.


    Thank you for using Ionicons!
  close: true
  lock: true
  dryRun: false
