
export type IconMap = {
  'ios-add-circle-outline': string;
  'ios-add-circle': string;
  'ios-add': string;
  'ios-airplane': string;
  'ios-alarm': string;
  'ios-albums': string;
  'ios-alert': string;
  'ios-american-football': string;
  'ios-analytics': string;
  'ios-aperture': string;
  'ios-apps': string;
  'ios-appstore': string;
  'ios-archive': string;
  'ios-arrow-back': string;
  'ios-arrow-down': string;
  'ios-arrow-dropdown-circle': string;
  'ios-arrow-dropdown': string;
  'ios-arrow-dropleft-circle': string;
  'ios-arrow-dropleft': string;
  'ios-arrow-dropright-circle': string;
  'ios-arrow-dropright': string;
  'ios-arrow-dropup-circle': string;
  'ios-arrow-dropup': string;
  'ios-arrow-forward': string;
  'ios-arrow-round-back': string;
  'ios-arrow-round-down': string;
  'ios-arrow-round-forward': string;
  'ios-arrow-round-up': string;
  'ios-arrow-up': string;
  'ios-at': string;
  'ios-attach': string;
  'ios-backspace': string;
  'ios-barcode': string;
  'ios-baseball': string;
  'ios-basket': string;
  'ios-basketball': string;
  'ios-battery-charging': string;
  'ios-battery-dead': string;
  'ios-battery-full': string;
  'ios-beaker': string;
  'ios-bed': string;
  'ios-beer': string;
  'ios-bicycle': string;
  'ios-bluetooth': string;
  'ios-boat': string;
  'ios-body': string;
  'ios-bonfire': string;
  'ios-book': string;
  'ios-bookmark': string;
  'ios-bookmarks': string;
  'ios-bowtie': string;
  'ios-briefcase': string;
  'ios-browsers': string;
  'ios-brush': string;
  'ios-bug': string;
  'ios-build': string;
  'ios-bulb': string;
  'ios-bus': string;
  'ios-business': string;
  'ios-cafe': string;
  'ios-calculator': string;
  'ios-calendar': string;
  'ios-call': string;
  'ios-camera': string;
  'ios-car': string;
  'ios-card': string;
  'ios-cart': string;
  'ios-cash': string;
  'ios-cellular': string;
  'ios-chatboxes': string;
  'ios-chatbubbles': string;
  'ios-checkbox-outline': string;
  'ios-checkbox': string;
  'ios-checkmark-circle-outline': string;
  'ios-checkmark-circle': string;
  'ios-checkmark': string;
  'ios-clipboard': string;
  'ios-clock': string;
  'ios-close-circle-outline': string;
  'ios-close-circle': string;
  'ios-close': string;
  'ios-cloud-circle': string;
  'ios-cloud-done': string;
  'ios-cloud-download': string;
  'ios-cloud-outline': string;
  'ios-cloud-upload': string;
  'ios-cloud': string;
  'ios-cloudy-night': string;
  'ios-cloudy': string;
  'ios-code-download': string;
  'ios-code-working': string;
  'ios-code': string;
  'ios-cog': string;
  'ios-color-fill': string;
  'ios-color-filter': string;
  'ios-color-palette': string;
  'ios-color-wand': string;
  'ios-compass': string;
  'ios-construct': string;
  'ios-contact': string;
  'ios-contacts': string;
  'ios-contract': string;
  'ios-contrast': string;
  'ios-copy': string;
  'ios-create': string;
  'ios-crop': string;
  'ios-cube': string;
  'ios-cut': string;
  'ios-desktop': string;
  'ios-disc': string;
  'ios-document': string;
  'ios-done-all': string;
  'ios-download': string;
  'ios-easel': string;
  'ios-egg': string;
  'ios-exit': string;
  'ios-expand': string;
  'ios-eye-off': string;
  'ios-eye': string;
  'ios-fastforward': string;
  'ios-female': string;
  'ios-filing': string;
  'ios-film': string;
  'ios-finger-print': string;
  'ios-fitness': string;
  'ios-flag': string;
  'ios-flame': string;
  'ios-flash-off': string;
  'ios-flash': string;
  'ios-flashlight': string;
  'ios-flask': string;
  'ios-flower': string;
  'ios-folder-open': string;
  'ios-folder': string;
  'ios-football': string;
  'ios-funnel': string;
  'ios-gift': string;
  'ios-git-branch': string;
  'ios-git-commit': string;
  'ios-git-compare': string;
  'ios-git-merge': string;
  'ios-git-network': string;
  'ios-git-pull-request': string;
  'ios-glasses': string;
  'ios-globe': string;
  'ios-grid': string;
  'ios-hammer': string;
  'ios-hand': string;
  'ios-happy': string;
  'ios-headset': string;
  'ios-heart-dislike': string;
  'ios-heart-empty': string;
  'ios-heart-half': string;
  'ios-heart': string;
  'ios-help-buoy': string;
  'ios-help-circle-outline': string;
  'ios-help-circle': string;
  'ios-help': string;
  'ios-home': string;
  'ios-hourglass': string;
  'ios-ice-cream': string;
  'ios-image': string;
  'ios-images': string;
  'ios-infinite': string;
  'ios-information-circle-outline': string;
  'ios-information-circle': string;
  'ios-information': string;
  'ios-jet': string;
  'ios-journal': string;
  'ios-key': string;
  'ios-keypad': string;
  'ios-laptop': string;
  'ios-leaf': string;
  'ios-link': string;
  'ios-list-box': string;
  'ios-list': string;
  'ios-locate': string;
  'ios-lock': string;
  'ios-log-in': string;
  'ios-log-out': string;
  'ios-magnet': string;
  'ios-mail-open': string;
  'ios-mail-unread': string;
  'ios-mail': string;
  'ios-male': string;
  'ios-man': string;
  'ios-map': string;
  'ios-medal': string;
  'ios-medical': string;
  'ios-medkit': string;
  'ios-megaphone': string;
  'ios-menu': string;
  'ios-mic-off': string;
  'ios-mic': string;
  'ios-microphone': string;
  'ios-moon': string;
  'ios-more': string;
  'ios-move': string;
  'ios-musical-note': string;
  'ios-musical-notes': string;
  'ios-navigate': string;
  'ios-notifications-off': string;
  'ios-notifications-outline': string;
  'ios-notifications': string;
  'ios-nuclear': string;
  'ios-nutrition': string;
  'ios-open': string;
  'ios-options': string;
  'ios-outlet': string;
  'ios-paper-plane': string;
  'ios-paper': string;
  'ios-partly-sunny': string;
  'ios-pause': string;
  'ios-paw': string;
  'ios-people': string;
  'ios-person-add': string;
  'ios-person': string;
  'ios-phone-landscape': string;
  'ios-phone-portrait': string;
  'ios-photos': string;
  'ios-pie': string;
  'ios-pin': string;
  'ios-pint': string;
  'ios-pizza': string;
  'ios-planet': string;
  'ios-play-circle': string;
  'ios-play': string;
  'ios-podium': string;
  'ios-power': string;
  'ios-pricetag': string;
  'ios-pricetags': string;
  'ios-print': string;
  'ios-pulse': string;
  'ios-qr-scanner': string;
  'ios-quote': string;
  'ios-radio-button-off': string;
  'ios-radio-button-on': string;
  'ios-radio': string;
  'ios-rainy': string;
  'ios-recording': string;
  'ios-redo': string;
  'ios-refresh-circle': string;
  'ios-refresh': string;
  'ios-remove-circle-outline': string;
  'ios-remove-circle': string;
  'ios-remove': string;
  'ios-reorder': string;
  'ios-repeat': string;
  'ios-resize': string;
  'ios-restaurant': string;
  'ios-return-left': string;
  'ios-return-right': string;
  'ios-reverse-camera': string;
  'ios-rewind': string;
  'ios-ribbon': string;
  'ios-rocket': string;
  'ios-rose': string;
  'ios-sad': string;
  'ios-save': string;
  'ios-school': string;
  'ios-search': string;
  'ios-send': string;
  'ios-settings': string;
  'ios-share-alt': string;
  'ios-share': string;
  'ios-shirt': string;
  'ios-shuffle': string;
  'ios-skip-backward': string;
  'ios-skip-forward': string;
  'ios-snow': string;
  'ios-speedometer': string;
  'ios-square-outline': string;
  'ios-square': string;
  'ios-star-half': string;
  'ios-star-outline': string;
  'ios-star': string;
  'ios-stats': string;
  'ios-stopwatch': string;
  'ios-subway': string;
  'ios-sunny': string;
  'ios-swap': string;
  'ios-switch': string;
  'ios-sync': string;
  'ios-tablet-landscape': string;
  'ios-tablet-portrait': string;
  'ios-tennisball': string;
  'ios-text': string;
  'ios-thermometer': string;
  'ios-thumbs-down': string;
  'ios-thumbs-up': string;
  'ios-thunderstorm': string;
  'ios-time': string;
  'ios-timer': string;
  'ios-today': string;
  'ios-train': string;
  'ios-transgender': string;
  'ios-trash': string;
  'ios-trending-down': string;
  'ios-trending-up': string;
  'ios-trophy': string;
  'ios-tv': string;
  'ios-umbrella': string;
  'ios-undo': string;
  'ios-unlock': string;
  'ios-videocam': string;
  'ios-volume-high': string;
  'ios-volume-low': string;
  'ios-volume-mute': string;
  'ios-volume-off': string;
  'ios-walk': string;
  'ios-wallet': string;
  'ios-warning': string;
  'ios-watch': string;
  'ios-water': string;
  'ios-wifi': string;
  'ios-wine': string;
  'ios-woman': string;
  'logo-android': string;
  'logo-angular': string;
  'logo-apple': string;
  'logo-bitbucket': string;
  'logo-bitcoin': string;
  'logo-buffer': string;
  'logo-chrome': string;
  'logo-closed-captioning': string;
  'logo-codepen': string;
  'logo-css3': string;
  'logo-designernews': string;
  'logo-dribbble': string;
  'logo-dropbox': string;
  'logo-euro': string;
  'logo-facebook': string;
  'logo-flickr': string;
  'logo-foursquare': string;
  'logo-freebsd-devil': string;
  'logo-game-controller-a': string;
  'logo-game-controller-b': string;
  'logo-github': string;
  'logo-google': string;
  'logo-googleplus': string;
  'logo-hackernews': string;
  'logo-html5': string;
  'logo-instagram': string;
  'logo-ionic': string;
  'logo-ionitron': string;
  'logo-javascript': string;
  'logo-linkedin': string;
  'logo-markdown': string;
  'logo-model-s': string;
  'logo-no-smoking': string;
  'logo-nodejs': string;
  'logo-npm': string;
  'logo-octocat': string;
  'logo-pinterest': string;
  'logo-playstation': string;
  'logo-polymer': string;
  'logo-python': string;
  'logo-reddit': string;
  'logo-rss': string;
  'logo-sass': string;
  'logo-skype': string;
  'logo-slack': string;
  'logo-snapchat': string;
  'logo-steam': string;
  'logo-tumblr': string;
  'logo-tux': string;
  'logo-twitch': string;
  'logo-twitter': string;
  'logo-usd': string;
  'logo-vimeo': string;
  'logo-vk': string;
  'logo-whatsapp': string;
  'logo-windows': string;
  'logo-wordpress': string;
  'logo-xbox': string;
  'logo-xing': string;
  'logo-yahoo': string;
  'logo-yen': string;
  'logo-youtube': string;
  'md-add-circle-outline': string;
  'md-add-circle': string;
  'md-add': string;
  'md-airplane': string;
  'md-alarm': string;
  'md-albums': string;
  'md-alert': string;
  'md-american-football': string;
  'md-analytics': string;
  'md-aperture': string;
  'md-apps': string;
  'md-appstore': string;
  'md-archive': string;
  'md-arrow-back': string;
  'md-arrow-down': string;
  'md-arrow-dropdown-circle': string;
  'md-arrow-dropdown': string;
  'md-arrow-dropleft-circle': string;
  'md-arrow-dropleft': string;
  'md-arrow-dropright-circle': string;
  'md-arrow-dropright': string;
  'md-arrow-dropup-circle': string;
  'md-arrow-dropup': string;
  'md-arrow-forward': string;
  'md-arrow-round-back': string;
  'md-arrow-round-down': string;
  'md-arrow-round-forward': string;
  'md-arrow-round-up': string;
  'md-arrow-up': string;
  'md-at': string;
  'md-attach': string;
  'md-backspace': string;
  'md-barcode': string;
  'md-baseball': string;
  'md-basket': string;
  'md-basketball': string;
  'md-battery-charging': string;
  'md-battery-dead': string;
  'md-battery-full': string;
  'md-beaker': string;
  'md-bed': string;
  'md-beer': string;
  'md-bicycle': string;
  'md-bluetooth': string;
  'md-boat': string;
  'md-body': string;
  'md-bonfire': string;
  'md-book': string;
  'md-bookmark': string;
  'md-bookmarks': string;
  'md-bowtie': string;
  'md-briefcase': string;
  'md-browsers': string;
  'md-brush': string;
  'md-bug': string;
  'md-build': string;
  'md-bulb': string;
  'md-bus': string;
  'md-business': string;
  'md-cafe': string;
  'md-calculator': string;
  'md-calendar': string;
  'md-call': string;
  'md-camera': string;
  'md-car': string;
  'md-card': string;
  'md-cart': string;
  'md-cash': string;
  'md-cellular': string;
  'md-chatboxes': string;
  'md-chatbubbles': string;
  'md-checkbox-outline': string;
  'md-checkbox': string;
  'md-checkmark-circle-outline': string;
  'md-checkmark-circle': string;
  'md-checkmark': string;
  'md-clipboard': string;
  'md-clock': string;
  'md-close-circle-outline': string;
  'md-close-circle': string;
  'md-close': string;
  'md-cloud-circle': string;
  'md-cloud-done': string;
  'md-cloud-download': string;
  'md-cloud-outline': string;
  'md-cloud-upload': string;
  'md-cloud': string;
  'md-cloudy-night': string;
  'md-cloudy': string;
  'md-code-download': string;
  'md-code-working': string;
  'md-code': string;
  'md-cog': string;
  'md-color-fill': string;
  'md-color-filter': string;
  'md-color-palette': string;
  'md-color-wand': string;
  'md-compass': string;
  'md-construct': string;
  'md-contact': string;
  'md-contacts': string;
  'md-contract': string;
  'md-contrast': string;
  'md-copy': string;
  'md-create': string;
  'md-crop': string;
  'md-cube': string;
  'md-cut': string;
  'md-desktop': string;
  'md-disc': string;
  'md-document': string;
  'md-done-all': string;
  'md-download': string;
  'md-easel': string;
  'md-egg': string;
  'md-exit': string;
  'md-expand': string;
  'md-eye-off': string;
  'md-eye': string;
  'md-fastforward': string;
  'md-female': string;
  'md-filing': string;
  'md-film': string;
  'md-finger-print': string;
  'md-fitness': string;
  'md-flag': string;
  'md-flame': string;
  'md-flash-off': string;
  'md-flash': string;
  'md-flashlight': string;
  'md-flask': string;
  'md-flower': string;
  'md-folder-open': string;
  'md-folder': string;
  'md-football': string;
  'md-funnel': string;
  'md-gift': string;
  'md-git-branch': string;
  'md-git-commit': string;
  'md-git-compare': string;
  'md-git-merge': string;
  'md-git-network': string;
  'md-git-pull-request': string;
  'md-glasses': string;
  'md-globe': string;
  'md-grid': string;
  'md-hammer': string;
  'md-hand': string;
  'md-happy': string;
  'md-headset': string;
  'md-heart-dislike': string;
  'md-heart-empty': string;
  'md-heart-half': string;
  'md-heart': string;
  'md-help-buoy': string;
  'md-help-circle-outline': string;
  'md-help-circle': string;
  'md-help': string;
  'md-home': string;
  'md-hourglass': string;
  'md-ice-cream': string;
  'md-image': string;
  'md-images': string;
  'md-infinite': string;
  'md-information-circle-outline': string;
  'md-information-circle': string;
  'md-information': string;
  'md-jet': string;
  'md-journal': string;
  'md-key': string;
  'md-keypad': string;
  'md-laptop': string;
  'md-leaf': string;
  'md-link': string;
  'md-list-box': string;
  'md-list': string;
  'md-locate': string;
  'md-lock': string;
  'md-log-in': string;
  'md-log-out': string;
  'md-magnet': string;
  'md-mail-open': string;
  'md-mail-unread': string;
  'md-mail': string;
  'md-male': string;
  'md-man': string;
  'md-map': string;
  'md-medal': string;
  'md-medical': string;
  'md-medkit': string;
  'md-megaphone': string;
  'md-menu': string;
  'md-mic-off': string;
  'md-mic': string;
  'md-microphone': string;
  'md-moon': string;
  'md-more': string;
  'md-move': string;
  'md-musical-note': string;
  'md-musical-notes': string;
  'md-navigate': string;
  'md-notifications-off': string;
  'md-notifications-outline': string;
  'md-notifications': string;
  'md-nuclear': string;
  'md-nutrition': string;
  'md-open': string;
  'md-options': string;
  'md-outlet': string;
  'md-paper-plane': string;
  'md-paper': string;
  'md-partly-sunny': string;
  'md-pause': string;
  'md-paw': string;
  'md-people': string;
  'md-person-add': string;
  'md-person': string;
  'md-phone-landscape': string;
  'md-phone-portrait': string;
  'md-photos': string;
  'md-pie': string;
  'md-pin': string;
  'md-pint': string;
  'md-pizza': string;
  'md-planet': string;
  'md-play-circle': string;
  'md-play': string;
  'md-podium': string;
  'md-power': string;
  'md-pricetag': string;
  'md-pricetags': string;
  'md-print': string;
  'md-pulse': string;
  'md-qr-scanner': string;
  'md-quote': string;
  'md-radio-button-off': string;
  'md-radio-button-on': string;
  'md-radio': string;
  'md-rainy': string;
  'md-recording': string;
  'md-redo': string;
  'md-refresh-circle': string;
  'md-refresh': string;
  'md-remove-circle-outline': string;
  'md-remove-circle': string;
  'md-remove': string;
  'md-reorder': string;
  'md-repeat': string;
  'md-resize': string;
  'md-restaurant': string;
  'md-return-left': string;
  'md-return-right': string;
  'md-reverse-camera': string;
  'md-rewind': string;
  'md-ribbon': string;
  'md-rocket': string;
  'md-rose': string;
  'md-sad': string;
  'md-save': string;
  'md-school': string;
  'md-search': string;
  'md-send': string;
  'md-settings': string;
  'md-share-alt': string;
  'md-share': string;
  'md-shirt': string;
  'md-shuffle': string;
  'md-skip-backward': string;
  'md-skip-forward': string;
  'md-snow': string;
  'md-speedometer': string;
  'md-square-outline': string;
  'md-square': string;
  'md-star-half': string;
  'md-star-outline': string;
  'md-star': string;
  'md-stats': string;
  'md-stopwatch': string;
  'md-subway': string;
  'md-sunny': string;
  'md-swap': string;
  'md-switch': string;
  'md-sync': string;
  'md-tablet-landscape': string;
  'md-tablet-portrait': string;
  'md-tennisball': string;
  'md-text': string;
  'md-thermometer': string;
  'md-thumbs-down': string;
  'md-thumbs-up': string;
  'md-thunderstorm': string;
  'md-time': string;
  'md-timer': string;
  'md-today': string;
  'md-train': string;
  'md-transgender': string;
  'md-trash': string;
  'md-trending-down': string;
  'md-trending-up': string;
  'md-trophy': string;
  'md-tv': string;
  'md-umbrella': string;
  'md-undo': string;
  'md-unlock': string;
  'md-videocam': string;
  'md-volume-high': string;
  'md-volume-low': string;
  'md-volume-mute': string;
  'md-volume-off': string;
  'md-walk': string;
  'md-wallet': string;
  'md-warning': string;
  'md-watch': string;
  'md-water': string;
  'md-wifi': string;
  'md-wine': string;
  'md-woman': string;
};

export type IconNames = keyof IconMap;

export declare const ICON_PATHS: IconMap;

export declare const iosAddCircleOutline: string;
export declare const iosAddCircle: string;
export declare const iosAdd: string;
export declare const iosAirplane: string;
export declare const iosAlarm: string;
export declare const iosAlbums: string;
export declare const iosAlert: string;
export declare const iosAmericanFootball: string;
export declare const iosAnalytics: string;
export declare const iosAperture: string;
export declare const iosApps: string;
export declare const iosAppstore: string;
export declare const iosArchive: string;
export declare const iosArrowBack: string;
export declare const iosArrowDown: string;
export declare const iosArrowDropdownCircle: string;
export declare const iosArrowDropdown: string;
export declare const iosArrowDropleftCircle: string;
export declare const iosArrowDropleft: string;
export declare const iosArrowDroprightCircle: string;
export declare const iosArrowDropright: string;
export declare const iosArrowDropupCircle: string;
export declare const iosArrowDropup: string;
export declare const iosArrowForward: string;
export declare const iosArrowRoundBack: string;
export declare const iosArrowRoundDown: string;
export declare const iosArrowRoundForward: string;
export declare const iosArrowRoundUp: string;
export declare const iosArrowUp: string;
export declare const iosAt: string;
export declare const iosAttach: string;
export declare const iosBackspace: string;
export declare const iosBarcode: string;
export declare const iosBaseball: string;
export declare const iosBasket: string;
export declare const iosBasketball: string;
export declare const iosBatteryCharging: string;
export declare const iosBatteryDead: string;
export declare const iosBatteryFull: string;
export declare const iosBeaker: string;
export declare const iosBed: string;
export declare const iosBeer: string;
export declare const iosBicycle: string;
export declare const iosBluetooth: string;
export declare const iosBoat: string;
export declare const iosBody: string;
export declare const iosBonfire: string;
export declare const iosBook: string;
export declare const iosBookmark: string;
export declare const iosBookmarks: string;
export declare const iosBowtie: string;
export declare const iosBriefcase: string;
export declare const iosBrowsers: string;
export declare const iosBrush: string;
export declare const iosBug: string;
export declare const iosBuild: string;
export declare const iosBulb: string;
export declare const iosBus: string;
export declare const iosBusiness: string;
export declare const iosCafe: string;
export declare const iosCalculator: string;
export declare const iosCalendar: string;
export declare const iosCall: string;
export declare const iosCamera: string;
export declare const iosCar: string;
export declare const iosCard: string;
export declare const iosCart: string;
export declare const iosCash: string;
export declare const iosCellular: string;
export declare const iosChatboxes: string;
export declare const iosChatbubbles: string;
export declare const iosCheckboxOutline: string;
export declare const iosCheckbox: string;
export declare const iosCheckmarkCircleOutline: string;
export declare const iosCheckmarkCircle: string;
export declare const iosCheckmark: string;
export declare const iosClipboard: string;
export declare const iosClock: string;
export declare const iosCloseCircleOutline: string;
export declare const iosCloseCircle: string;
export declare const iosClose: string;
export declare const iosCloudCircle: string;
export declare const iosCloudDone: string;
export declare const iosCloudDownload: string;
export declare const iosCloudOutline: string;
export declare const iosCloudUpload: string;
export declare const iosCloud: string;
export declare const iosCloudyNight: string;
export declare const iosCloudy: string;
export declare const iosCodeDownload: string;
export declare const iosCodeWorking: string;
export declare const iosCode: string;
export declare const iosCog: string;
export declare const iosColorFill: string;
export declare const iosColorFilter: string;
export declare const iosColorPalette: string;
export declare const iosColorWand: string;
export declare const iosCompass: string;
export declare const iosConstruct: string;
export declare const iosContact: string;
export declare const iosContacts: string;
export declare const iosContract: string;
export declare const iosContrast: string;
export declare const iosCopy: string;
export declare const iosCreate: string;
export declare const iosCrop: string;
export declare const iosCube: string;
export declare const iosCut: string;
export declare const iosDesktop: string;
export declare const iosDisc: string;
export declare const iosDocument: string;
export declare const iosDoneAll: string;
export declare const iosDownload: string;
export declare const iosEasel: string;
export declare const iosEgg: string;
export declare const iosExit: string;
export declare const iosExpand: string;
export declare const iosEyeOff: string;
export declare const iosEye: string;
export declare const iosFastforward: string;
export declare const iosFemale: string;
export declare const iosFiling: string;
export declare const iosFilm: string;
export declare const iosFingerPrint: string;
export declare const iosFitness: string;
export declare const iosFlag: string;
export declare const iosFlame: string;
export declare const iosFlashOff: string;
export declare const iosFlash: string;
export declare const iosFlashlight: string;
export declare const iosFlask: string;
export declare const iosFlower: string;
export declare const iosFolderOpen: string;
export declare const iosFolder: string;
export declare const iosFootball: string;
export declare const iosFunnel: string;
export declare const iosGift: string;
export declare const iosGitBranch: string;
export declare const iosGitCommit: string;
export declare const iosGitCompare: string;
export declare const iosGitMerge: string;
export declare const iosGitNetwork: string;
export declare const iosGitPullRequest: string;
export declare const iosGlasses: string;
export declare const iosGlobe: string;
export declare const iosGrid: string;
export declare const iosHammer: string;
export declare const iosHand: string;
export declare const iosHappy: string;
export declare const iosHeadset: string;
export declare const iosHeartDislike: string;
export declare const iosHeartEmpty: string;
export declare const iosHeartHalf: string;
export declare const iosHeart: string;
export declare const iosHelpBuoy: string;
export declare const iosHelpCircleOutline: string;
export declare const iosHelpCircle: string;
export declare const iosHelp: string;
export declare const iosHome: string;
export declare const iosHourglass: string;
export declare const iosIceCream: string;
export declare const iosImage: string;
export declare const iosImages: string;
export declare const iosInfinite: string;
export declare const iosInformationCircleOutline: string;
export declare const iosInformationCircle: string;
export declare const iosInformation: string;
export declare const iosJet: string;
export declare const iosJournal: string;
export declare const iosKey: string;
export declare const iosKeypad: string;
export declare const iosLaptop: string;
export declare const iosLeaf: string;
export declare const iosLink: string;
export declare const iosListBox: string;
export declare const iosList: string;
export declare const iosLocate: string;
export declare const iosLock: string;
export declare const iosLogIn: string;
export declare const iosLogOut: string;
export declare const iosMagnet: string;
export declare const iosMailOpen: string;
export declare const iosMailUnread: string;
export declare const iosMail: string;
export declare const iosMale: string;
export declare const iosMan: string;
export declare const iosMap: string;
export declare const iosMedal: string;
export declare const iosMedical: string;
export declare const iosMedkit: string;
export declare const iosMegaphone: string;
export declare const iosMenu: string;
export declare const iosMicOff: string;
export declare const iosMic: string;
export declare const iosMicrophone: string;
export declare const iosMoon: string;
export declare const iosMore: string;
export declare const iosMove: string;
export declare const iosMusicalNote: string;
export declare const iosMusicalNotes: string;
export declare const iosNavigate: string;
export declare const iosNotificationsOff: string;
export declare const iosNotificationsOutline: string;
export declare const iosNotifications: string;
export declare const iosNuclear: string;
export declare const iosNutrition: string;
export declare const iosOpen: string;
export declare const iosOptions: string;
export declare const iosOutlet: string;
export declare const iosPaperPlane: string;
export declare const iosPaper: string;
export declare const iosPartlySunny: string;
export declare const iosPause: string;
export declare const iosPaw: string;
export declare const iosPeople: string;
export declare const iosPersonAdd: string;
export declare const iosPerson: string;
export declare const iosPhoneLandscape: string;
export declare const iosPhonePortrait: string;
export declare const iosPhotos: string;
export declare const iosPie: string;
export declare const iosPin: string;
export declare const iosPint: string;
export declare const iosPizza: string;
export declare const iosPlanet: string;
export declare const iosPlayCircle: string;
export declare const iosPlay: string;
export declare const iosPodium: string;
export declare const iosPower: string;
export declare const iosPricetag: string;
export declare const iosPricetags: string;
export declare const iosPrint: string;
export declare const iosPulse: string;
export declare const iosQrScanner: string;
export declare const iosQuote: string;
export declare const iosRadioButtonOff: string;
export declare const iosRadioButtonOn: string;
export declare const iosRadio: string;
export declare const iosRainy: string;
export declare const iosRecording: string;
export declare const iosRedo: string;
export declare const iosRefreshCircle: string;
export declare const iosRefresh: string;
export declare const iosRemoveCircleOutline: string;
export declare const iosRemoveCircle: string;
export declare const iosRemove: string;
export declare const iosReorder: string;
export declare const iosRepeat: string;
export declare const iosResize: string;
export declare const iosRestaurant: string;
export declare const iosReturnLeft: string;
export declare const iosReturnRight: string;
export declare const iosReverseCamera: string;
export declare const iosRewind: string;
export declare const iosRibbon: string;
export declare const iosRocket: string;
export declare const iosRose: string;
export declare const iosSad: string;
export declare const iosSave: string;
export declare const iosSchool: string;
export declare const iosSearch: string;
export declare const iosSend: string;
export declare const iosSettings: string;
export declare const iosShareAlt: string;
export declare const iosShare: string;
export declare const iosShirt: string;
export declare const iosShuffle: string;
export declare const iosSkipBackward: string;
export declare const iosSkipForward: string;
export declare const iosSnow: string;
export declare const iosSpeedometer: string;
export declare const iosSquareOutline: string;
export declare const iosSquare: string;
export declare const iosStarHalf: string;
export declare const iosStarOutline: string;
export declare const iosStar: string;
export declare const iosStats: string;
export declare const iosStopwatch: string;
export declare const iosSubway: string;
export declare const iosSunny: string;
export declare const iosSwap: string;
export declare const iosSwitch: string;
export declare const iosSync: string;
export declare const iosTabletLandscape: string;
export declare const iosTabletPortrait: string;
export declare const iosTennisball: string;
export declare const iosText: string;
export declare const iosThermometer: string;
export declare const iosThumbsDown: string;
export declare const iosThumbsUp: string;
export declare const iosThunderstorm: string;
export declare const iosTime: string;
export declare const iosTimer: string;
export declare const iosToday: string;
export declare const iosTrain: string;
export declare const iosTransgender: string;
export declare const iosTrash: string;
export declare const iosTrendingDown: string;
export declare const iosTrendingUp: string;
export declare const iosTrophy: string;
export declare const iosTv: string;
export declare const iosUmbrella: string;
export declare const iosUndo: string;
export declare const iosUnlock: string;
export declare const iosVideocam: string;
export declare const iosVolumeHigh: string;
export declare const iosVolumeLow: string;
export declare const iosVolumeMute: string;
export declare const iosVolumeOff: string;
export declare const iosWalk: string;
export declare const iosWallet: string;
export declare const iosWarning: string;
export declare const iosWatch: string;
export declare const iosWater: string;
export declare const iosWifi: string;
export declare const iosWine: string;
export declare const iosWoman: string;
export declare const logoAndroid: string;
export declare const logoAngular: string;
export declare const logoApple: string;
export declare const logoBitbucket: string;
export declare const logoBitcoin: string;
export declare const logoBuffer: string;
export declare const logoChrome: string;
export declare const logoClosedCaptioning: string;
export declare const logoCodepen: string;
export declare const logoCss3: string;
export declare const logoDesignernews: string;
export declare const logoDribbble: string;
export declare const logoDropbox: string;
export declare const logoEuro: string;
export declare const logoFacebook: string;
export declare const logoFlickr: string;
export declare const logoFoursquare: string;
export declare const logoFreebsdDevil: string;
export declare const logoGameControllerA: string;
export declare const logoGameControllerB: string;
export declare const logoGithub: string;
export declare const logoGoogle: string;
export declare const logoGoogleplus: string;
export declare const logoHackernews: string;
export declare const logoHtml5: string;
export declare const logoInstagram: string;
export declare const logoIonic: string;
export declare const logoIonitron: string;
export declare const logoJavascript: string;
export declare const logoLinkedin: string;
export declare const logoMarkdown: string;
export declare const logoModelS: string;
export declare const logoNoSmoking: string;
export declare const logoNodejs: string;
export declare const logoNpm: string;
export declare const logoOctocat: string;
export declare const logoPinterest: string;
export declare const logoPlaystation: string;
export declare const logoPolymer: string;
export declare const logoPython: string;
export declare const logoReddit: string;
export declare const logoRss: string;
export declare const logoSass: string;
export declare const logoSkype: string;
export declare const logoSlack: string;
export declare const logoSnapchat: string;
export declare const logoSteam: string;
export declare const logoTumblr: string;
export declare const logoTux: string;
export declare const logoTwitch: string;
export declare const logoTwitter: string;
export declare const logoUsd: string;
export declare const logoVimeo: string;
export declare const logoVk: string;
export declare const logoWhatsapp: string;
export declare const logoWindows: string;
export declare const logoWordpress: string;
export declare const logoXbox: string;
export declare const logoXing: string;
export declare const logoYahoo: string;
export declare const logoYen: string;
export declare const logoYoutube: string;
export declare const mdAddCircleOutline: string;
export declare const mdAddCircle: string;
export declare const mdAdd: string;
export declare const mdAirplane: string;
export declare const mdAlarm: string;
export declare const mdAlbums: string;
export declare const mdAlert: string;
export declare const mdAmericanFootball: string;
export declare const mdAnalytics: string;
export declare const mdAperture: string;
export declare const mdApps: string;
export declare const mdAppstore: string;
export declare const mdArchive: string;
export declare const mdArrowBack: string;
export declare const mdArrowDown: string;
export declare const mdArrowDropdownCircle: string;
export declare const mdArrowDropdown: string;
export declare const mdArrowDropleftCircle: string;
export declare const mdArrowDropleft: string;
export declare const mdArrowDroprightCircle: string;
export declare const mdArrowDropright: string;
export declare const mdArrowDropupCircle: string;
export declare const mdArrowDropup: string;
export declare const mdArrowForward: string;
export declare const mdArrowRoundBack: string;
export declare const mdArrowRoundDown: string;
export declare const mdArrowRoundForward: string;
export declare const mdArrowRoundUp: string;
export declare const mdArrowUp: string;
export declare const mdAt: string;
export declare const mdAttach: string;
export declare const mdBackspace: string;
export declare const mdBarcode: string;
export declare const mdBaseball: string;
export declare const mdBasket: string;
export declare const mdBasketball: string;
export declare const mdBatteryCharging: string;
export declare const mdBatteryDead: string;
export declare const mdBatteryFull: string;
export declare const mdBeaker: string;
export declare const mdBed: string;
export declare const mdBeer: string;
export declare const mdBicycle: string;
export declare const mdBluetooth: string;
export declare const mdBoat: string;
export declare const mdBody: string;
export declare const mdBonfire: string;
export declare const mdBook: string;
export declare const mdBookmark: string;
export declare const mdBookmarks: string;
export declare const mdBowtie: string;
export declare const mdBriefcase: string;
export declare const mdBrowsers: string;
export declare const mdBrush: string;
export declare const mdBug: string;
export declare const mdBuild: string;
export declare const mdBulb: string;
export declare const mdBus: string;
export declare const mdBusiness: string;
export declare const mdCafe: string;
export declare const mdCalculator: string;
export declare const mdCalendar: string;
export declare const mdCall: string;
export declare const mdCamera: string;
export declare const mdCar: string;
export declare const mdCard: string;
export declare const mdCart: string;
export declare const mdCash: string;
export declare const mdCellular: string;
export declare const mdChatboxes: string;
export declare const mdChatbubbles: string;
export declare const mdCheckboxOutline: string;
export declare const mdCheckbox: string;
export declare const mdCheckmarkCircleOutline: string;
export declare const mdCheckmarkCircle: string;
export declare const mdCheckmark: string;
export declare const mdClipboard: string;
export declare const mdClock: string;
export declare const mdCloseCircleOutline: string;
export declare const mdCloseCircle: string;
export declare const mdClose: string;
export declare const mdCloudCircle: string;
export declare const mdCloudDone: string;
export declare const mdCloudDownload: string;
export declare const mdCloudOutline: string;
export declare const mdCloudUpload: string;
export declare const mdCloud: string;
export declare const mdCloudyNight: string;
export declare const mdCloudy: string;
export declare const mdCodeDownload: string;
export declare const mdCodeWorking: string;
export declare const mdCode: string;
export declare const mdCog: string;
export declare const mdColorFill: string;
export declare const mdColorFilter: string;
export declare const mdColorPalette: string;
export declare const mdColorWand: string;
export declare const mdCompass: string;
export declare const mdConstruct: string;
export declare const mdContact: string;
export declare const mdContacts: string;
export declare const mdContract: string;
export declare const mdContrast: string;
export declare const mdCopy: string;
export declare const mdCreate: string;
export declare const mdCrop: string;
export declare const mdCube: string;
export declare const mdCut: string;
export declare const mdDesktop: string;
export declare const mdDisc: string;
export declare const mdDocument: string;
export declare const mdDoneAll: string;
export declare const mdDownload: string;
export declare const mdEasel: string;
export declare const mdEgg: string;
export declare const mdExit: string;
export declare const mdExpand: string;
export declare const mdEyeOff: string;
export declare const mdEye: string;
export declare const mdFastforward: string;
export declare const mdFemale: string;
export declare const mdFiling: string;
export declare const mdFilm: string;
export declare const mdFingerPrint: string;
export declare const mdFitness: string;
export declare const mdFlag: string;
export declare const mdFlame: string;
export declare const mdFlashOff: string;
export declare const mdFlash: string;
export declare const mdFlashlight: string;
export declare const mdFlask: string;
export declare const mdFlower: string;
export declare const mdFolderOpen: string;
export declare const mdFolder: string;
export declare const mdFootball: string;
export declare const mdFunnel: string;
export declare const mdGift: string;
export declare const mdGitBranch: string;
export declare const mdGitCommit: string;
export declare const mdGitCompare: string;
export declare const mdGitMerge: string;
export declare const mdGitNetwork: string;
export declare const mdGitPullRequest: string;
export declare const mdGlasses: string;
export declare const mdGlobe: string;
export declare const mdGrid: string;
export declare const mdHammer: string;
export declare const mdHand: string;
export declare const mdHappy: string;
export declare const mdHeadset: string;
export declare const mdHeartDislike: string;
export declare const mdHeartEmpty: string;
export declare const mdHeartHalf: string;
export declare const mdHeart: string;
export declare const mdHelpBuoy: string;
export declare const mdHelpCircleOutline: string;
export declare const mdHelpCircle: string;
export declare const mdHelp: string;
export declare const mdHome: string;
export declare const mdHourglass: string;
export declare const mdIceCream: string;
export declare const mdImage: string;
export declare const mdImages: string;
export declare const mdInfinite: string;
export declare const mdInformationCircleOutline: string;
export declare const mdInformationCircle: string;
export declare const mdInformation: string;
export declare const mdJet: string;
export declare const mdJournal: string;
export declare const mdKey: string;
export declare const mdKeypad: string;
export declare const mdLaptop: string;
export declare const mdLeaf: string;
export declare const mdLink: string;
export declare const mdListBox: string;
export declare const mdList: string;
export declare const mdLocate: string;
export declare const mdLock: string;
export declare const mdLogIn: string;
export declare const mdLogOut: string;
export declare const mdMagnet: string;
export declare const mdMailOpen: string;
export declare const mdMailUnread: string;
export declare const mdMail: string;
export declare const mdMale: string;
export declare const mdMan: string;
export declare const mdMap: string;
export declare const mdMedal: string;
export declare const mdMedical: string;
export declare const mdMedkit: string;
export declare const mdMegaphone: string;
export declare const mdMenu: string;
export declare const mdMicOff: string;
export declare const mdMic: string;
export declare const mdMicrophone: string;
export declare const mdMoon: string;
export declare const mdMore: string;
export declare const mdMove: string;
export declare const mdMusicalNote: string;
export declare const mdMusicalNotes: string;
export declare const mdNavigate: string;
export declare const mdNotificationsOff: string;
export declare const mdNotificationsOutline: string;
export declare const mdNotifications: string;
export declare const mdNuclear: string;
export declare const mdNutrition: string;
export declare const mdOpen: string;
export declare const mdOptions: string;
export declare const mdOutlet: string;
export declare const mdPaperPlane: string;
export declare const mdPaper: string;
export declare const mdPartlySunny: string;
export declare const mdPause: string;
export declare const mdPaw: string;
export declare const mdPeople: string;
export declare const mdPersonAdd: string;
export declare const mdPerson: string;
export declare const mdPhoneLandscape: string;
export declare const mdPhonePortrait: string;
export declare const mdPhotos: string;
export declare const mdPie: string;
export declare const mdPin: string;
export declare const mdPint: string;
export declare const mdPizza: string;
export declare const mdPlanet: string;
export declare const mdPlayCircle: string;
export declare const mdPlay: string;
export declare const mdPodium: string;
export declare const mdPower: string;
export declare const mdPricetag: string;
export declare const mdPricetags: string;
export declare const mdPrint: string;
export declare const mdPulse: string;
export declare const mdQrScanner: string;
export declare const mdQuote: string;
export declare const mdRadioButtonOff: string;
export declare const mdRadioButtonOn: string;
export declare const mdRadio: string;
export declare const mdRainy: string;
export declare const mdRecording: string;
export declare const mdRedo: string;
export declare const mdRefreshCircle: string;
export declare const mdRefresh: string;
export declare const mdRemoveCircleOutline: string;
export declare const mdRemoveCircle: string;
export declare const mdRemove: string;
export declare const mdReorder: string;
export declare const mdRepeat: string;
export declare const mdResize: string;
export declare const mdRestaurant: string;
export declare const mdReturnLeft: string;
export declare const mdReturnRight: string;
export declare const mdReverseCamera: string;
export declare const mdRewind: string;
export declare const mdRibbon: string;
export declare const mdRocket: string;
export declare const mdRose: string;
export declare const mdSad: string;
export declare const mdSave: string;
export declare const mdSchool: string;
export declare const mdSearch: string;
export declare const mdSend: string;
export declare const mdSettings: string;
export declare const mdShareAlt: string;
export declare const mdShare: string;
export declare const mdShirt: string;
export declare const mdShuffle: string;
export declare const mdSkipBackward: string;
export declare const mdSkipForward: string;
export declare const mdSnow: string;
export declare const mdSpeedometer: string;
export declare const mdSquareOutline: string;
export declare const mdSquare: string;
export declare const mdStarHalf: string;
export declare const mdStarOutline: string;
export declare const mdStar: string;
export declare const mdStats: string;
export declare const mdStopwatch: string;
export declare const mdSubway: string;
export declare const mdSunny: string;
export declare const mdSwap: string;
export declare const mdSwitch: string;
export declare const mdSync: string;
export declare const mdTabletLandscape: string;
export declare const mdTabletPortrait: string;
export declare const mdTennisball: string;
export declare const mdText: string;
export declare const mdThermometer: string;
export declare const mdThumbsDown: string;
export declare const mdThumbsUp: string;
export declare const mdThunderstorm: string;
export declare const mdTime: string;
export declare const mdTimer: string;
export declare const mdToday: string;
export declare const mdTrain: string;
export declare const mdTransgender: string;
export declare const mdTrash: string;
export declare const mdTrendingDown: string;
export declare const mdTrendingUp: string;
export declare const mdTrophy: string;
export declare const mdTv: string;
export declare const mdUmbrella: string;
export declare const mdUndo: string;
export declare const mdUnlock: string;
export declare const mdVideocam: string;
export declare const mdVolumeHigh: string;
export declare const mdVolumeLow: string;
export declare const mdVolumeMute: string;
export declare const mdVolumeOff: string;
export declare const mdWalk: string;
export declare const mdWallet: string;
export declare const mdWarning: string;
export declare const mdWatch: string;
export declare const mdWater: string;
export declare const mdWifi: string;
export declare const mdWine: string;
export declare const mdWoman: string;
