name: 💡 Feature Request
description: Suggest a new feature for the ion-icon component. Icon requests should use the "Icon Request" template instead.
labels: ["triage"]
title: "feat: "
body:
  - type: textarea
    attributes:
      label: Describe Problem
      description: A clear and concise description of what the problem is. Ex. I am always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe Preferred Solution
      description: A clear and concise description of what you want to happen.
  - type: textarea
    attributes:
      label: Describe Alternatives
      description: A clear and concise description of any alternative solutions or features you have considered.
  - type: textarea
    attributes:
      label: Additional Information
      description: Add any other context or screenshots about the feature request here.