/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
} from '@stencil/router';


export namespace Components {

  interface IonIcon {
    /**
    * Specifies the label to use for accessibility. Defaults to the icon name.
    */
    'ariaLabel'?: string;
    /**
    * The color to use for the background of the item.
    */
    'color'?: string;
    /**
    * A combination of both `name` and `src`. If a `src` url is detected it will set the `src` property. Otherwise it assumes it's a built-in named SVG and set the `name` property.
    */
    'icon'?: string;
    /**
    * Specifies which icon to use on `ios` mode.
    */
    'ios'?: string;
    /**
    * If enabled, ion-icon will be loaded lazily when it's visible in the viewport. Default, `false`.
    */
    'lazy': boolean;
    /**
    * Specifies which icon to use on `md` mode.
    */
    'md'?: string;
    /**
    * The mode determines which platform styles to use. Possible values are: `"ios"` or `"md"`.
    */
    'mode'?: 'ios' | 'md';
    /**
    * Specifies which icon to use from the built-in set of icons.
    */
    'name'?: string;
    /**
    * The size of the icon. Available options are: `"small"` and `"large"`.
    */
    'size'?: string;
    /**
    * Specifies the exact `src` of an SVG file to use.
    */
    'src'?: string;
  }
  interface IonIconAttributes extends StencilHTMLAttributes {
    /**
    * Specifies the label to use for accessibility. Defaults to the icon name.
    */
    'ariaLabel'?: string;
    /**
    * The color to use for the background of the item.
    */
    'color'?: string;
    /**
    * A combination of both `name` and `src`. If a `src` url is detected it will set the `src` property. Otherwise it assumes it's a built-in named SVG and set the `name` property.
    */
    'icon'?: string;
    /**
    * Specifies which icon to use on `ios` mode.
    */
    'ios'?: string;
    /**
    * If enabled, ion-icon will be loaded lazily when it's visible in the viewport. Default, `false`.
    */
    'lazy'?: boolean;
    /**
    * Specifies which icon to use on `md` mode.
    */
    'md'?: string;
    /**
    * The mode determines which platform styles to use. Possible values are: `"ios"` or `"md"`.
    */
    'mode'?: 'ios' | 'md';
    /**
    * Specifies which icon to use from the built-in set of icons.
    */
    'name'?: string;
    /**
    * The size of the icon. Available options are: `"small"` and `"large"`.
    */
    'size'?: string;
    /**
    * Specifies the exact `src` of an SVG file to use.
    */
    'src'?: string;
  }

  interface FooterBar {}
  interface FooterBarAttributes extends StencilHTMLAttributes {}

  interface HeaderBar {
    'isSearchVisible': boolean;
    'query': string;
    'version': string;
  }
  interface HeaderBarAttributes extends StencilHTMLAttributes {
    'isSearchVisible'?: boolean;
    'onToggleHeaderSearch'?: (event: CustomEvent) => void;
    'query'?: string;
    'version'?: string;
  }

  interface IconList {
    'data': any;
    'query': string;
  }
  interface IconListAttributes extends StencilHTMLAttributes {
    'data'?: any;
    'query'?: string;
  }

  interface IconSearch {
    'autofocus': string;
    'query': string;
    'size': string;
  }
  interface IconSearchAttributes extends StencilHTMLAttributes {
    'autofocus'?: string;
    'onHasSearched'?: (event: CustomEvent) => void;
    'query'?: string;
    'size'?: string;
  }

  interface IoniconsSite {}
  interface IoniconsSiteAttributes extends StencilHTMLAttributes {}

  interface LandingPage {
    'data': any;
    'query': string;
  }
  interface LandingPageAttributes extends StencilHTMLAttributes {
    'data'?: any;
    'query'?: string;
  }

  interface NotfoundPage {}
  interface NotfoundPageAttributes extends StencilHTMLAttributes {}

  interface ToastBar {
    'selectedIcon': {
      name: string,
      icons: string[],
      tags: string[]
    };
    'selectedIconType': string;
  }
  interface ToastBarAttributes extends StencilHTMLAttributes {
    'onClearToast'?: (event: CustomEvent) => void;
    'onToggleHeaderSearch'?: (event: CustomEvent) => void;
    'selectedIcon'?: {
      name: string,
      icons: string[],
      tags: string[]
    };
    'selectedIconType'?: string;
  }

  interface UsagePage {
    'data': any;
    'match'?: MatchResults;
  }
  interface UsagePageAttributes extends StencilHTMLAttributes {
    'data'?: any;
    'match'?: MatchResults;
  }
}

declare global {
  interface StencilElementInterfaces {
    'IonIcon': Components.IonIcon;
    'FooterBar': Components.FooterBar;
    'HeaderBar': Components.HeaderBar;
    'IconList': Components.IconList;
    'IconSearch': Components.IconSearch;
    'IoniconsSite': Components.IoniconsSite;
    'LandingPage': Components.LandingPage;
    'NotfoundPage': Components.NotfoundPage;
    'ToastBar': Components.ToastBar;
    'UsagePage': Components.UsagePage;
  }

  interface StencilIntrinsicElements {
    'ion-icon': Components.IonIconAttributes;
    'footer-bar': Components.FooterBarAttributes;
    'header-bar': Components.HeaderBarAttributes;
    'icon-list': Components.IconListAttributes;
    'icon-search': Components.IconSearchAttributes;
    'ionicons-site': Components.IoniconsSiteAttributes;
    'landing-page': Components.LandingPageAttributes;
    'notfound-page': Components.NotfoundPageAttributes;
    'toast-bar': Components.ToastBarAttributes;
    'usage-page': Components.UsagePageAttributes;
  }


  interface HTMLIonIconElement extends Components.IonIcon, HTMLStencilElement {}
  var HTMLIonIconElement: {
    prototype: HTMLIonIconElement;
    new (): HTMLIonIconElement;
  };

  interface HTMLFooterBarElement extends Components.FooterBar, HTMLStencilElement {}
  var HTMLFooterBarElement: {
    prototype: HTMLFooterBarElement;
    new (): HTMLFooterBarElement;
  };

  interface HTMLHeaderBarElement extends Components.HeaderBar, HTMLStencilElement {}
  var HTMLHeaderBarElement: {
    prototype: HTMLHeaderBarElement;
    new (): HTMLHeaderBarElement;
  };

  interface HTMLIconListElement extends Components.IconList, HTMLStencilElement {}
  var HTMLIconListElement: {
    prototype: HTMLIconListElement;
    new (): HTMLIconListElement;
  };

  interface HTMLIconSearchElement extends Components.IconSearch, HTMLStencilElement {}
  var HTMLIconSearchElement: {
    prototype: HTMLIconSearchElement;
    new (): HTMLIconSearchElement;
  };

  interface HTMLIoniconsSiteElement extends Components.IoniconsSite, HTMLStencilElement {}
  var HTMLIoniconsSiteElement: {
    prototype: HTMLIoniconsSiteElement;
    new (): HTMLIoniconsSiteElement;
  };

  interface HTMLLandingPageElement extends Components.LandingPage, HTMLStencilElement {}
  var HTMLLandingPageElement: {
    prototype: HTMLLandingPageElement;
    new (): HTMLLandingPageElement;
  };

  interface HTMLNotfoundPageElement extends Components.NotfoundPage, HTMLStencilElement {}
  var HTMLNotfoundPageElement: {
    prototype: HTMLNotfoundPageElement;
    new (): HTMLNotfoundPageElement;
  };

  interface HTMLToastBarElement extends Components.ToastBar, HTMLStencilElement {}
  var HTMLToastBarElement: {
    prototype: HTMLToastBarElement;
    new (): HTMLToastBarElement;
  };

  interface HTMLUsagePageElement extends Components.UsagePage, HTMLStencilElement {}
  var HTMLUsagePageElement: {
    prototype: HTMLUsagePageElement;
    new (): HTMLUsagePageElement;
  };

  interface HTMLElementTagNameMap {
    'ion-icon': HTMLIonIconElement
    'footer-bar': HTMLFooterBarElement
    'header-bar': HTMLHeaderBarElement
    'icon-list': HTMLIconListElement
    'icon-search': HTMLIconSearchElement
    'ionicons-site': HTMLIoniconsSiteElement
    'landing-page': HTMLLandingPageElement
    'notfound-page': HTMLNotfoundPageElement
    'toast-bar': HTMLToastBarElement
    'usage-page': HTMLUsagePageElement
  }

  interface ElementTagNameMap {
    'ion-icon': HTMLIonIconElement;
    'footer-bar': HTMLFooterBarElement;
    'header-bar': HTMLHeaderBarElement;
    'icon-list': HTMLIconListElement;
    'icon-search': HTMLIconSearchElement;
    'ionicons-site': HTMLIoniconsSiteElement;
    'landing-page': HTMLLandingPageElement;
    'notfound-page': HTMLNotfoundPageElement;
    'toast-bar': HTMLToastBarElement;
    'usage-page': HTMLUsagePageElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
