name: 'Test Spec'
description: 'Test Spec'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Cache Node Modules
      uses: actions/cache@v2
      env:
        cache-name: node-modules
      with:
        path: ./node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./package-lock.json') }}-v2
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionicons-build
        filename: IoniconsBuild.zip
    - name: Test
      run: npm run test.spec -- --ci
      shell: bash
